In [1]:
import numpy as np

In [2]:
import math as m

In [55]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [15]:
type([a])

list

In [17]:
# Q1: How many negative numbers are there?
np.arange(int(a))

TypeError: only size-1 arrays can be converted to Python scalars

In [32]:
# Q2: How many positive numbers are there?
a[a > 0]
# 5

array([ 4, 10, 12, 23,  3])

In [39]:
# Q3: How many even positive numbers are there?
a[(a > 0) & (a % 2 ==0)]
# 3

array([ 4, 10, 12])

In [ ]:
# Q4: If you were to add 3 to each data point, how many positive numbers would there be?
# 10

In [40]:
a += 3
print(a)

[ 7 13 15 26  1  2  3  3  3 -3  6 -4]


In [41]:
a[a > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [56]:
a.mean()

3.0

In [69]:
a.std()

8.06225774829855

In [71]:
stds = a.std()
print(stds)

8.06225774829855


In [58]:
# Q5: If you squared each number, what would the new mean and standard deviation be?
# mean 3 goes to 74 and std goes from 8.1 to 144

In [59]:
b = a**2
print(a**2)

[ 16 100 144 529   4   1   0   0   0  36   9  49]


In [60]:
b.mean()

74.0

In [61]:
b.std()

144.0243035046516

In [62]:
print(a)

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]


In [ ]:
# Q6: A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0.
# This is done by subtracting the mean from each data point. Center the data set.

In [63]:
center = a - a.mean()

In [66]:
middle = center.mean()
print(middle)

0.0


In [ ]:
# Q7: Calculate the z-score for each data point. Recall that the z-score is given by:

In [74]:
score = center / stds
print(score)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


In [75]:
score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
# Q8: Copy the setup and exercise directions from More Numpy Practice 
# into your numpy_exercises.py and add your solutions.

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]